//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RQsortCompet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int _MAX_STACK_DEPTH {
            get {
                return ((int)(this["_MAX_STACK_DEPTH"]));
            }
            set {
                this["_MAX_STACK_DEPTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"D:\\Users\\Nale\\Desktop\\alghw\\input\"")]
        public string _DEFAULT_INPUT_DIRECTORY {
            get {
                return ((string)(this["_DEFAULT_INPUT_DIRECTORY"]));
            }
            set {
                this["_DEFAULT_INPUT_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"D:\\Users\\Nale\\Desktop\\alghw\\output\"")]
        public string _DEFAULT_OUTPUT_DIRECTORY {
            get {
                return ((string)(this["_DEFAULT_OUTPUT_DIRECTORY"]));
            }
            set {
                this["_DEFAULT_OUTPUT_DIRECTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int _SWITCH_THRESHOLD {
            get {
                return ((int)(this["_SWITCH_THRESHOLD"]));
            }
            set {
                this["_SWITCH_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62914560")]
        public long _MAX_DATA_SIZE {
            get {
                return ((long)(this["_MAX_DATA_SIZE"]));
            }
            set {
                this["_MAX_DATA_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int _INI_STACK_DEPTH {
            get {
                return ((int)(this["_INI_STACK_DEPTH"]));
            }
            set {
                this["_INI_STACK_DEPTH"] = value;
            }
        }
    }
}
